/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'
import { Route as SettingsToolsRouteImport } from './routes/settings.tools'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsMaintenanceRouteImport } from './routes/settings.maintenance'
import { Route as SettingsConfigRouteImport } from './routes/settings.config'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as WorkflowIdIndexRouteImport } from './routes/workflow.$id.index'
import { Route as WorkflowIdRunsRunIdRouteImport } from './routes/workflow.$id.runs.$runId'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowRoute,
} as any)
const SettingsToolsRoute = SettingsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMaintenanceRoute = SettingsMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConfigRoute = SettingsConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdIndexRoute = WorkflowIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowIdRoute,
} as any)
const WorkflowIdRunsRunIdRoute = WorkflowIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => WorkflowIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/automation': typeof AutomationRoute
  '/board': typeof BoardRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/workflow': typeof WorkflowRouteWithChildren
  '/c/$id': typeof CIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/config': typeof SettingsConfigRoute
  '/settings/maintenance': typeof SettingsMaintenanceRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/workflow/$id': typeof WorkflowIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/workflow/$id/': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/automation': typeof AutomationRoute
  '/board': typeof BoardRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$id': typeof CIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/config': typeof SettingsConfigRoute
  '/settings/maintenance': typeof SettingsMaintenanceRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/workflow/$id': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/automation': typeof AutomationRoute
  '/board': typeof BoardRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/workflow': typeof WorkflowRouteWithChildren
  '/c/$id': typeof CIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/config': typeof SettingsConfigRoute
  '/settings/maintenance': typeof SettingsMaintenanceRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/workflow/$id': typeof WorkflowIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/workflow/$id/': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/artifacts'
    | '/automation'
    | '/board'
    | '/live'
    | '/logs'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/workflow'
    | '/c/$id'
    | '/projects/$id'
    | '/settings/config'
    | '/settings/maintenance'
    | '/settings/mcp'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/tools'
    | '/workflow/$id'
    | '/projects/'
    | '/settings/'
    | '/workflow/'
    | '/workflow/$id/'
    | '/workflow/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/artifacts'
    | '/automation'
    | '/board'
    | '/live'
    | '/logs'
    | '/memory'
    | '/skills'
    | '/tasks'
    | '/c/$id'
    | '/projects/$id'
    | '/settings/config'
    | '/settings/maintenance'
    | '/settings/mcp'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/tools'
    | '/projects'
    | '/settings'
    | '/workflow'
    | '/workflow/$id'
    | '/workflow/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/artifacts'
    | '/automation'
    | '/board'
    | '/live'
    | '/logs'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/workflow'
    | '/c/$id'
    | '/projects/$id'
    | '/settings/config'
    | '/settings/maintenance'
    | '/settings/mcp'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/tools'
    | '/workflow/$id'
    | '/projects/'
    | '/settings/'
    | '/workflow/'
    | '/workflow/$id/'
    | '/workflow/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ArtifactsRoute: typeof ArtifactsRoute
  AutomationRoute: typeof AutomationRoute
  BoardRoute: typeof BoardRoute
  LiveRoute: typeof LiveRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  WorkflowRoute: typeof WorkflowRouteWithChildren
  CIdRoute: typeof CIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/settings/tools': {
      id: '/settings/tools'
      path: '/tools'
      fullPath: '/settings/tools'
      preLoaderRoute: typeof SettingsToolsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/maintenance': {
      id: '/settings/maintenance'
      path: '/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof SettingsMaintenanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/config': {
      id: '/settings/config'
      path: '/config'
      fullPath: '/settings/config'
      preLoaderRoute: typeof SettingsConfigRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id/': {
      id: '/workflow/$id/'
      path: '/'
      fullPath: '/workflow/$id/'
      preLoaderRoute: typeof WorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowIdRoute
    }
    '/workflow/$id/runs/$runId': {
      id: '/workflow/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflow/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowIdRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsConfigRoute: typeof SettingsConfigRoute
  SettingsMaintenanceRoute: typeof SettingsMaintenanceRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsToolsRoute: typeof SettingsToolsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsConfigRoute: SettingsConfigRoute,
  SettingsMaintenanceRoute: SettingsMaintenanceRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsToolsRoute: SettingsToolsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkflowIdRouteChildren {
  WorkflowIdIndexRoute: typeof WorkflowIdIndexRoute
  WorkflowIdRunsRunIdRoute: typeof WorkflowIdRunsRunIdRoute
}

const WorkflowIdRouteChildren: WorkflowIdRouteChildren = {
  WorkflowIdIndexRoute: WorkflowIdIndexRoute,
  WorkflowIdRunsRunIdRoute: WorkflowIdRunsRunIdRoute,
}

const WorkflowIdRouteWithChildren = WorkflowIdRoute._addFileChildren(
  WorkflowIdRouteChildren,
)

interface WorkflowRouteChildren {
  WorkflowIdRoute: typeof WorkflowIdRouteWithChildren
  WorkflowIndexRoute: typeof WorkflowIndexRoute
}

const WorkflowRouteChildren: WorkflowRouteChildren = {
  WorkflowIdRoute: WorkflowIdRouteWithChildren,
  WorkflowIndexRoute: WorkflowIndexRoute,
}

const WorkflowRouteWithChildren = WorkflowRoute._addFileChildren(
  WorkflowRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  ArtifactsRoute: ArtifactsRoute,
  AutomationRoute: AutomationRoute,
  BoardRoute: BoardRoute,
  LiveRoute: LiveRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  WorkflowRoute: WorkflowRouteWithChildren,
  CIdRoute: CIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
