/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as WorkflowIdIndexRouteImport } from './routes/workflow.$id.index'
import { Route as WorkflowIdRunsRunIdRouteImport } from './routes/workflow.$id.runs.$runId'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdIndexRoute = WorkflowIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowIdRoute,
} as any)
const WorkflowIdRunsRunIdRoute = WorkflowIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => WorkflowIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/automation': typeof AutomationRoute
  '/board': typeof BoardRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/workflow': typeof WorkflowRouteWithChildren
  '/c/$id': typeof CIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/workflow/$id': typeof WorkflowIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/workflow/$id/': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/automation': typeof AutomationRoute
  '/board': typeof BoardRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$id': typeof CIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/workflow/$id': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/automation': typeof AutomationRoute
  '/board': typeof BoardRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/workflow': typeof WorkflowRouteWithChildren
  '/c/$id': typeof CIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/workflow/$id': typeof WorkflowIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/workflow/$id/': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/automation'
    | '/board'
    | '/live'
    | '/logs'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/workflow'
    | '/c/$id'
    | '/projects/$id'
    | '/workflow/$id'
    | '/projects/'
    | '/workflow/'
    | '/workflow/$id/'
    | '/workflow/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/automation'
    | '/board'
    | '/live'
    | '/logs'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$id'
    | '/projects/$id'
    | '/projects'
    | '/workflow'
    | '/workflow/$id'
    | '/workflow/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/automation'
    | '/board'
    | '/live'
    | '/logs'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/workflow'
    | '/c/$id'
    | '/projects/$id'
    | '/workflow/$id'
    | '/projects/'
    | '/workflow/'
    | '/workflow/$id/'
    | '/workflow/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  AutomationRoute: typeof AutomationRoute
  BoardRoute: typeof BoardRoute
  LiveRoute: typeof LiveRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  WorkflowRoute: typeof WorkflowRouteWithChildren
  CIdRoute: typeof CIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id/': {
      id: '/workflow/$id/'
      path: '/'
      fullPath: '/workflow/$id/'
      preLoaderRoute: typeof WorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowIdRoute
    }
    '/workflow/$id/runs/$runId': {
      id: '/workflow/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflow/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowIdRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface WorkflowIdRouteChildren {
  WorkflowIdIndexRoute: typeof WorkflowIdIndexRoute
  WorkflowIdRunsRunIdRoute: typeof WorkflowIdRunsRunIdRoute
}

const WorkflowIdRouteChildren: WorkflowIdRouteChildren = {
  WorkflowIdIndexRoute: WorkflowIdIndexRoute,
  WorkflowIdRunsRunIdRoute: WorkflowIdRunsRunIdRoute,
}

const WorkflowIdRouteWithChildren = WorkflowIdRoute._addFileChildren(
  WorkflowIdRouteChildren,
)

interface WorkflowRouteChildren {
  WorkflowIdRoute: typeof WorkflowIdRouteWithChildren
  WorkflowIndexRoute: typeof WorkflowIndexRoute
}

const WorkflowRouteChildren: WorkflowRouteChildren = {
  WorkflowIdRoute: WorkflowIdRouteWithChildren,
  WorkflowIndexRoute: WorkflowIndexRoute,
}

const WorkflowRouteWithChildren = WorkflowRoute._addFileChildren(
  WorkflowRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  AutomationRoute: AutomationRoute,
  BoardRoute: BoardRoute,
  LiveRoute: LiveRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  WorkflowRoute: WorkflowRouteWithChildren,
  CIdRoute: CIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
