/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as WorkflowIdIndexRouteImport } from './routes/workflow.$id.index'
import { Route as WorkflowIdRunsRunIdRouteImport } from './routes/workflow.$id.runs.$runId'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowRoute,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowRoute,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdIndexRoute = WorkflowIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowIdRoute,
} as any)
const WorkflowIdRunsRunIdRoute = WorkflowIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => WorkflowIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/live': typeof LiveRoute
  '/tasks': typeof TasksRoute
  '/workflow': typeof WorkflowRouteWithChildren
  '/c/$id': typeof CIdRoute
  '/workflow/$id': typeof WorkflowIdRouteWithChildren
  '/workflow/': typeof WorkflowIndexRoute
  '/workflow/$id/': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/live': typeof LiveRoute
  '/tasks': typeof TasksRoute
  '/c/$id': typeof CIdRoute
  '/workflow': typeof WorkflowIndexRoute
  '/workflow/$id': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/live': typeof LiveRoute
  '/tasks': typeof TasksRoute
  '/workflow': typeof WorkflowRouteWithChildren
  '/c/$id': typeof CIdRoute
  '/workflow/$id': typeof WorkflowIdRouteWithChildren
  '/workflow/': typeof WorkflowIndexRoute
  '/workflow/$id/': typeof WorkflowIdIndexRoute
  '/workflow/$id/runs/$runId': typeof WorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/live'
    | '/tasks'
    | '/workflow'
    | '/c/$id'
    | '/workflow/$id'
    | '/workflow/'
    | '/workflow/$id/'
    | '/workflow/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/live'
    | '/tasks'
    | '/c/$id'
    | '/workflow'
    | '/workflow/$id'
    | '/workflow/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/live'
    | '/tasks'
    | '/workflow'
    | '/c/$id'
    | '/workflow/$id'
    | '/workflow/'
    | '/workflow/$id/'
    | '/workflow/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  LiveRoute: typeof LiveRoute
  TasksRoute: typeof TasksRoute
  WorkflowRoute: typeof WorkflowRouteWithChildren
  CIdRoute: typeof CIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id/': {
      id: '/workflow/$id/'
      path: '/'
      fullPath: '/workflow/$id/'
      preLoaderRoute: typeof WorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowIdRoute
    }
    '/workflow/$id/runs/$runId': {
      id: '/workflow/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflow/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowIdRoute
    }
  }
}

interface WorkflowIdRouteChildren {
  WorkflowIdIndexRoute: typeof WorkflowIdIndexRoute
  WorkflowIdRunsRunIdRoute: typeof WorkflowIdRunsRunIdRoute
}

const WorkflowIdRouteChildren: WorkflowIdRouteChildren = {
  WorkflowIdIndexRoute: WorkflowIdIndexRoute,
  WorkflowIdRunsRunIdRoute: WorkflowIdRunsRunIdRoute,
}

const WorkflowIdRouteWithChildren = WorkflowIdRoute._addFileChildren(
  WorkflowIdRouteChildren,
)

interface WorkflowRouteChildren {
  WorkflowIdRoute: typeof WorkflowIdRouteWithChildren
  WorkflowIndexRoute: typeof WorkflowIndexRoute
}

const WorkflowRouteChildren: WorkflowRouteChildren = {
  WorkflowIdRoute: WorkflowIdRouteWithChildren,
  WorkflowIndexRoute: WorkflowIndexRoute,
}

const WorkflowRouteWithChildren = WorkflowRoute._addFileChildren(
  WorkflowRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  LiveRoute: LiveRoute,
  TasksRoute: TasksRoute,
  WorkflowRoute: WorkflowRouteWithChildren,
  CIdRoute: CIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
